# -*- coding: utf-8 -*-
"""Olist_RFM Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VfCW_kk8XFw1KDIuo2kjsFMiP7KfJCrT
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
import datetime

try:
    orders = pd.read_csv('olist_orders_dataset.csv')
    items = pd.read_csv('olist_order_items_dataset.csv')
    customers = pd.read_csv('olist_customers_dataset.csv')

    print("✅ Success! All 3 files are loaded.")
    print(f"Orders count: {len(orders)}")
    print(f"Items count: {len(items)}")
    print(f"Customers count: {len(customers)}")

except FileNotFoundError:
    print("❌ Error: I can't find the files.")

# --- ACTION 1: TIME TRAVEL FIX (Convert to Datetime) ---
# We need this to calculate "Recency" later
orders['order_purchase_timestamp'] = pd.to_datetime(orders['order_purchase_timestamp'])

# --- ACTION 2: QUALITY CONTROL (Filter for Delivered) ---
orders_clean = orders[orders['order_status'] == 'delivered']

# --- ACTION 3: THE DOUBLE BRIDGE (Merging) ---
orders_items = pd.merge(orders_clean, items, on='order_id', how='inner')
master_df = pd.merge(orders_items, customers, on='customer_id', how='inner')

# --- VERIFICATION ---
print("✅ Phase 1 Complete!")
print(f"Master DataFrame Shape: {master_df.shape}")
print("\n--- Preview of the Master Data ---")
# We select just the 3 columns we care about to verify they exist
print(master_df[['customer_unique_id', 'order_purchase_timestamp', 'price']].head())

master_df.head()

import datetime as dt

# --- LANGKAH 1: BUAT TANGGAL PATOKAN ---
max_date = master_df['order_purchase_timestamp'].max() + dt.timedelta(days=1)
print(f"Tanggal Patokan Analisis: {max_date}")

# --- LANGKAH 2: MENGHITUNG RFM (GROUPBY) ---
rfm_df = master_df.groupby('customer_unique_id').agg({
    'order_purchase_timestamp': lambda x: (max_date - x.max()).days,
    'order_id': 'count',
    'price': 'sum'
}).reset_index()

# --- LANGKAH 3: RAPIKAN TABEL ---
rfm_df.columns = ['customer_id', 'Recency', 'Frequency', 'Monetary']

# --- LANGKAH 4: CEK HASIL ---
print("\n--- Contoh 5 Data Teratas ---")
print(rfm_df.head())

print("\n--- Statistik Data (Perhatikan Kolom Frequency!) ---")
print(rfm_df.describe())

# --- FASE 3: SCORING (PEMBERIAN NILAI 1-5) ---
r_labels = range(5, 0, -1) # [5, 4, 3, 2, 1]
f_labels = range(1, 6)     # [1, 2, 3, 4, 5]
m_labels = range(1, 6)     # [1, 2, 3, 4, 5]

# 2. Hitung R Score (Recency)
rfm_df['R_Score'] = pd.qcut(rfm_df['Recency'], q=5, labels=r_labels)

# 3. Hitung F Score (Frequency) - PAKAI TRIK RANKING
rfm_df['F_Score'] = pd.qcut(rfm_df['Frequency'].rank(method='first'), q=5, labels=f_labels)

# 4. Hitung M Score (Monetary)
rfm_df['M_Score'] = pd.qcut(rfm_df['Monetary'], q=5, labels=m_labels)

# 5. Gabungkan Score Jadi Satu String (Contoh: "555")
rfm_df['RFM_Segment'] = rfm_df['R_Score'].astype(str) + rfm_df['F_Score'].astype(str) + rfm_df['M_Score'].astype(str)

# 6. Buat Kolom Total Score (Angka)
rfm_df['RFM_Score_Total'] = rfm_df[['R_Score', 'F_Score', 'M_Score']].sum(axis=1)

# --- CEK HASILNYA ---
print("--- Contoh Hasil Scoring ---")
print(rfm_df[['customer_id', 'Recency', 'Frequency', 'Monetary', 'RFM_Segment', 'RFM_Score_Total']].head())

# --- FASE 4: PEMBERIAN LABEL MANUSIA ---

def assign_label(score):
    if score >= 13:
        return 'Champions'
    elif score >= 10:
        return 'Loyal'
    elif score >= 7:
        return 'Potential'
    elif score >= 4:
        return 'At Risk'
    else:
        return 'Lost'


rfm_df['Customer_Segment'] = rfm_df['RFM_Score_Total'].apply(assign_label)

# --- CEK HASIL AKHIR ---
print("--- Distribusi Segmen Pelanggan ---")
print(rfm_df['Customer_Segment'].value_counts())

# --- FASE 5: EXPORT KE CSV (UNTUK POWER BI) ---
rfm_df.to_csv('rfm_analysis_result.csv', index=False)

print("\n✅ File 'rfm_analysis_result.csv' berhasil dibuat!")
print("Silakan download file ini dari panel Files di sebelah kiri.")

